apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: harvester-vm-dhcp-controller
  namespace: harvester-system
  labels:
    addon.harvesterhci.io/experimental: "true"
spec:
  enabled: false
  repo: https://charts.harvesterhci.io
  version: "v0.1.0"
  chart: harvester-vm-dhcp-controller
  valuesContent: |
    image:
      tag: v0.1.0
    agent:
      image:
        tag: v0.1.0
    webhook:
      image:
        tag: v0.1.0
