---
apiVersion: v1
kind: Namespace
metadata:
  name: rancher-vcluster
---
apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: rancher-vcluster
  namespace: rancher-vcluster
  labels:
    addon.harvesterhci.io/experimental: "true"
spec:
  enabled: false
  repo: https://charts.loft.sh
  version: v0.27.0
  chart: vcluster
  valuesContent: |-
    serviceCIDR: 10.53.0.0/16
    controlPlane:
      distro:
        k3s:
          resources:
            limits:
              memory: 16096Mi
              cpu: 8000m
          enabled: true
          imagePullPolicy: IfNotPresent
          image:
            tag: v1.33.4-k3s1
            repository: rancher/k3s
    sync:
      toHost:
        ingresses:
          enabled: true
    experimental:
      deploy:
        vcluster:
          manifests: |-
            apiVersion: v1
            kind: Namespace
            metadata:
              name: cattle-system
            ---
            apiVersion: v1
            kind: Namespace
            metadata:
              name: cert-manager
              labels:
                certmanager.k8s.io/disable-validation: "true"
          helm:
            - chart:
                name: cert-manager
                repo: https://charts.jetstack.io
                version: v1.8.0
              release:
                name: cert-manager
                namespace: cert-manager
              values: |-
                installCRDs: true

            - chart:
                name: rancher
                repo: https://releases.rancher.com/server-charts/latest
                version: v2.12.0
              release:
                name: rancher
                namespace: cattle-system
              values: |-
                hostname: rancher.192.168.0.131.sslip.io
                replicas: 1
                bootstrapPassword: password1234
                rancherImage: rancher/rancher
                ingress:
                  tls:
                    source: rancher
                global:
                  cattle:
                    psp:
                      enabled: "false"
                extraEnv:
                  - name: CATTLE_AGENT_IMAGE
                    value: rancher/rancher-agent:v2.12.0
