---
apiVersion: v1
kind: Namespace
metadata:
  name: rancher-vcluster
---
apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: rancher-vcluster
  namespace: rancher-vcluster
  labels:
    addon.harvesterhci.io/experimental: "true"
spec:
  enabled: false
  repo: https://charts.loft.sh
  version: "v0.30.0"
  chart: vcluster
  valuesContent: |-
    global:
      hostname: ""
      rancherVersion: v2.13.2
      bootstrapPassword: ""

    sync:
      toHost:
        ingresses:
          enabled: true

    controlPlane:
      distro:
        k3s:
          enabled: true
          image:
            registry: ""
            repository: "rancher/k3s"
            tag: "v1.34.2-k3s1"
          securityContext: {}
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 40m
              memory: 64Mi
      backingStore:
        database:
          embedded:
            enabled: true

      statefulSet:
        image:
          registry: "ghcr.io"
          repository: "loft-sh/vcluster-pro"
          tag: "0.30.0"
        resources:
          # Limits are resource limits for the container
          limits:
            ephemeral-storage: 10Gi
            memory: 4Gi
          # Requests are minimal resources that will be consumed by the container
          requests:
            ephemeral-storage: 1Gi
            cpu: 200m
            memory: 256Mi

    experimental:
      deploy:
        vcluster:
          manifestsTemplate: |-
            apiVersion: v1
            kind: Namespace
            metadata:
              name: cattle-system
            ---
            apiVersion: v1
            kind: Namespace
            metadata:
              name: cert-manager
              labels:
                certmanager.k8s.io/disable-validation: "true"
            ---
            apiVersion: helm.cattle.io/v1
            kind: HelmChart
            metadata:
              name: cert-manager
              namespace: kube-system
            spec:
              targetNamespace: cert-manager
              repo: https://charts.jetstack.io
              chart: cert-manager
              version: v1.18.5
              helmVersion: v3
              set:
                crds.enabled: "true"
            ---
            apiVersion: helm.cattle.io/v1
            kind: HelmChart
            metadata:
              name: rancher
              namespace: kube-system
            spec:
              targetNamespace: cattle-system
              repo: https://releases.rancher.com/server-charts/latest
              chart: rancher
              version: {{ .Values.global.rancherVersion }}
              set:
                ingress.tls.source: rancher
                hostname: {{ .Values.global.hostname }}
                replicas: 1
                global.cattle.psp.enabled: "false"
                bootstrapPassword: {{ .Values.global.bootstrapPassword }}
              helmVersion: v3
