---
apiVersion: v1
kind: Namespace
metadata:
  name: k3k-system
---
apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: k3k
  namespace: k3k-system
spec:
  enabled: false
  repo: https://rancher.github.io/k3k
  version: "v1.1.0"
  chart: k3k
  valuesContent: ""